### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by akalicki** [vimeo/ABLincoln#7]
Think about renaming repository to better establish relationship between original PlanOut release and PHP port (e.g. keep ABLincoln as an internal use name and release repo as PlanOut-PHP)

- [ ] rename repo [has to be done by organization admin]
- [ ] re-link with Packagist after name change (if it doesn't update automatically)
- [ ] update PHP file namespacing
- [ ] update README references with new name

**Comment by akalicki** [comment]
Any word on this @jacoboliver? I can do everything but the repo rename, which has to be done by an organization admin.

**Comment by jacoboliver** [comment]
@akalicki I don't think we'll be changing the name of ABLincoln. From here on we will probably diverge from what is in PlanOut with our own (PHP specific) use cases - things like adding a datastore, the companion javascript piece, immediate results, and more.
