### ISSUE TITLE
Implement checksum method

### ISSUE THREAD

**Issue by akalicki** [vimeo/ABLincoln#8]

**Comment by eytan** [comment]
I think the checksum is cute but not really necessary.  If you did implement it, I wonder if it could be a trait or something.

**Comment by akalicki** [comment]
Yeah, Vimeo's not using it but I wasn't sure whether it had seen any use elsewhere. I'll close this for now and look back into it if I hear of a good use case.

**Comment by gety9** [comment]
@eytan why it not useful? It's a way to see if experiment was changed. (planout docs at least recommend using it this way)

Without checksum how would detect that?

p.s. just starting with planout, so i maybe wrong.

**Comment by gety9** [comment]
@akalicki seems like checksum was never added. How would you see if experiment was changed without it?
